### ISSUE TITLE
i don't know why,but travis always build error with a log "An error occurred while generating the build script."

### ISSUE THREAD

**Issue by naivor** [travis-ci/beta-features#14]
this can not  see  any thing,and my .travis.yml  is succeed in http://lint.travis-ci.org/,I don't know what happend. Here is my  cofig:
```
language: android

sudo: false

notifications:
  email: false

jdk:
  - oraclejdk8
  
android:
  components:
        -build-tools-25.0.2
        -android-25

        - extra-android-m2repository
        - extra-android-support

        - platform-tools
        - tools

        - add-on
        - extra

before_install:     
 - chmod +x gradlew

script:
     - ./gradlew assembleRelease
```
