### ISSUE TITLE
explicit matrix for stages

### ISSUE THREAD

**Issue by noahdesu** [travis-ci/beta-features#18]
I would like to do something like the following where the `prepare` stage runs with default setting, and the `test` stage runs with a matrix of explicitly specified configurations. this doesn't work, but i'm not sure how to achieve what i'm looking for. thanks.

```
  include:
    - stage: prepare
      script:
        - echo "prepare"
    - stage: test
      matrix:
        include:
          - os: linux
            compiler: gcc
          - os: linux
            env: DOCKER_IMAGE=centos:7
          - os: linux
            env: DOCKER_IMAGE=fedora:25
          - os: linux
            env: DOCKER_IMAGE=fedora:24
      script:
        - echo "test with ${DOCKER_IMAGE}"
```
