### ISSUE TITLE
Php projects build under versions 7.0 and 7.1 

### ISSUE THREAD

**Issue by masterjus** [travis-ci/beta-features#33]
I've decided to write this bug here as this is beta feature issue:

I try to build my project under php versions 7.0 and 7.1 but this how build looks like

![image](https://user-images.githubusercontent.com/464043/31939050-ef6751ee-b8c1-11e7-982b-5ca5a672b759.png)

So it's running tests for 7.0 twice but never doing build for php 7.1

My .travis.yml
```yml
sudo: true
language: php
php:
  - '7.0'
  - '7.1'

before_script:
  - sudo add-apt-repository ppa:ondrej/php -y
  - sudo apt-get update -yy
  - sudo apt-get install -y php-bcmath
  - composer install -o -q

jobs:
  include:
    - stage: build
      install:
        - composer require edgedesign/phpqa --update-no-dev --no-progress -q
      script:
        - ./vendor/bin/phpqa --analyzedDirs src --report --buildDir ./docs --tools phpcs:0,phpmd,phpcpd:0,phpmetrics:0,phploc,pdepend
    - stage: test
      script:
        - phpunit
```
