### ISSUE TITLE
build stage: configuration not intuitive

### ISSUE THREAD

**Issue by bochen2014** [travis-ci/beta-features#35]
I can understand how build stage is current designed. It's just not intuitive. the structure suggests that one stage can only contain one script, and if you want more than one scripts in one stage, you need to define a new script *following* current stage, whilst it should be defined **within** the stage,  isn't it?

would below configuration makes more sense?
```yml
job:
  stage:
  - name: stage1
    jobs:
    - script 1
    - script 2
  - name: stage2
    jobs:
    - script 3
    - script 4
```

**Comment by maticzav** [comment]
Actually, as far as I understand this, you can specify multiple jobs, just by inserting them without `stage` property.
```yaml
# From the examples
jobs:
  include:
    - stage: test
      script: ./test 1
    - # stage name not required, will continue to use `test`
      script: ./test 2
    - stage: deploy
      script: ./deploy
```

So the equivalent of your code, should, I suppose, be:
```yaml
jobs:
  include:
    - stage: stage1
       script: script1
       script: script2
    - stage: stage2
       script: script3
       script: script4
```

I do agree though, that it could be done better. I love how `circleci` implemented this using `deployment` property instead of `jobs` and assigning specifics there.  
```yaml
deployment:
  production:
    branch: production
    commands:
      - cmd1
      - cmd2
```

**Comment by bochen2014** [comment]
I dont thinks its a valid ymal file
```yml
jobs:
  include:
    - stage: stage1
       script: script1
       script: script2
    - stage: stage2
       script: script3
       script: script4
```

**Comment by maticzav** [comment]
sorry, correct **yaml** file:
```yaml
jobs:
  include:
    - stage: stage1
      script: script1
      script: script2
    - stage: stage2
      script: script3
      script: script4
```
