### ISSUE TITLE
Problem with conditional jobs

### ISSUE THREAD

**Issue by tooomm** [travis-ci/beta-features#40]
This is about the beta feature [Conditional Builds, Stages, and Jobs](https://docs.travis-ci.com/user/conditional-builds-stages-jobs).

I have conditional jobs setup in my build matrix like (travis.yml)

```
matrix:
  include:
  - os: linux
    env: BUILDTYPE=Debug
  - os: linux
    env: BUILDTYPE=Release
    if: (branch = master AND NOT type = pull_request) OR tag IS present
```

That works fine with what I try to accomplish:
- run `Release` type builds for
     - all builds from `master` branch (but not for PR's against `master`!)
     - all tagged commits

Problem is that I want to prevent `Debug` builds for tags in return.
I tried with what the documentation gives me, but it did not work.

All of this `if:` statements still created a `Debug` job:
```
  - os: linux
    env: BUILDTYPE=Debug
    if: tag IS blank
  - os: linux
    env: BUILDTYPE=Debug
    if: tag IS NOT present
  - os: linux
    env: BUILDTYPE=Debug
    if: tag NOT present
```
Also, using `env(TRAVIS_TAG)` instead `tag` didn't help.

Any suggestions? Did I run into an issue/bug?
It's confusing because `tag IS present` seems to work for my configuration for `Release` as shown above.
