### ISSUE TITLE
Use of Build Stages, Extra Python Job

### ISSUE THREAD

**Issue by gmr** [travis-ci/beta-features#41]
When using Build Stages, given the following config:

```yaml
sudo: false
language: python
python:
 - 2.7
 - 3.4
 - 3.5
 - 3.6
 - pypy
 - pypy3
install:
 - pip install awscli
 - pip install -r requires/testing.txt
 - python setup.py develop
stages:
 - test
 - name: upload_coverage
   if: branch = master
 - name: deploy
   if: tag IS present
script: nosetests
jobs:
  include:
   - stage: test
     services:
     - postgres
     script: nosetests
```
For the test stage there are 2 jobs created for Python 2.7.   So for stage "Test" I will see:
 - 2.7
 - 3.4
 - 3.5
 - 3.6
 - pypy
 - pypy3
 - 2.7

You can see this in two different projects:

- https://travis-ci.org/gmr/queries/builds/332966217
https://travis-ci.org/gmr/rejected/builds/332076424

**Comment by gmr** [comment]
Another example:

![duplicated 2 6](https://user-images.githubusercontent.com/49469/35589324-73854614-05d1-11e8-951f-c5e2e5cb6283.png)

**Comment by gmr** [comment]
From what I can tell this relates to #42.

It appears that all jobs but the last one in the list are run in the high-level "test" job/stage. The last entry is run in the "jobs > includes" definition as they don't seem to allow a list of python versions to use and default to the first one if no version is specified.

To get this to work as I would expect I ended up with this short-hand version of the .travis.yml:
```yaml
language: python
stages:
- test
- coverage
- name: deploy
  if: tag IS present
script: nosetests
jobs:
  include:
   - python: 2.7
   - python: 3.4
   - python: 3.5
   - python: 3.6
   - stage: coverage
     python: 3.6
     install:
     - pip install awscli coverage codecov
     script:
     - Do my coverage stuff here
     after_success: codecov
   - stage: deploy
     python: 3.6
     script: true
     deploy:
       distributions: sdist bdist_wheel
```
